name: shoryan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  geocoding: ^5.0.0

  # State Management
  flutter_bloc: ^9.1.1

  # HTTP Client
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3
  get_it: ^7.7.0

  # Environment Variables
  flutter_dotenv: ^6.0.0

  # Localization
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  geolocator: ^14.0.3
  flutter_map: ^8.3.1
  latlong2: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env